# Generated by Django 3.1.4 on 2020-12-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='file_description',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
