# Generated by Django 3.1.4 on 2020-12-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_file_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='file_description',
        ),
    ]
