# Generated by Django 3.1.4 on 2020-12-17 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='sold_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
