# Generated by Django 3.1.4 on 2020-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201218_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
