# Generated by Django 3.1.4 on 2020-12-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_cart',
        ),
    ]
