# Generated by Django 3.1.4 on 2020-12-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201218_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_to',
        ),
    ]
